name: "Run tests and build with Maven on the maven-build branch"

on:
  push:
    branches:
    - "maven-build"

jobs:
  build:
    name: "Test and Build with Maven"
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
    - name: "Checkout repository"
      uses: actions/checkout@v7
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: "Set up JDK 11"
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 11

    - name: "Build binaries with mvn"
      run: mvn package
      
    - name: "Upload artifact"
      uses: actions/upload-artifact@v4
      with:
        name: fat-zip       # name shown in the Actions UI and the name of the artefact itself + .zip!
        path: target/magellan*.zip  # file, folder, or glob pattern to upload
        overwrite: true
